sudo: true
language: python
matrix:
  include:
  - python: 3.6
  - python: 3.7
  - python: 3.8
cache:
  pip: true
  directories:
    - ".venv"
branches:
  only:
  - master
  - /^v\d+\.\d+\.\d+.*$/
before_install:
  - curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python -
  - source $HOME/.poetry/env
  - poetry --version
install:
  - poetry install -v
script:
  - make test-ci
deploy:
  provider: script
  script: poetry publish --build -u __token__ -p $PYPI_TOKEN
  skip_cleanup: true
  skip_existing: true
  on:
    tags: true
    branch: master
    python: "3.6"
